### ISSUE TITLE
Potential runtime panics detected by static analysis

### ISSUE THREAD

**Issue by lizhuohua** [mir-protocol/r1cs#11]
It is possible to construct malformed data structures or function arguments to trigger runtime panics.
For example, this triggers a division-by-zero in function `integer_division_ceil`:
```rust
use r1cs::Bn128;
use r1cs::Element;
use r1cs::MdsMatrix;
use r1cs::RescueBuilder;

fn main() {
    let mut builder = RescueBuilder::<Bn128>::new(0);
    let matrix = MdsMatrix::<Bn128>::new(vec![vec![Element::zero()]]);
    builder.mds_matrix(matrix);
    builder.build();
}
```
And the following triggers an out-of-range access in function `ElementMatrix::new`:
```rust
use r1cs::Bn128;
use r1cs::MdsMatrix;

fn main() {
    MdsMatrix::<Bn128>::new(vec![]);
}
```

**Comment by dlubarov** [comment]
Hi, thanks for the report. I think it makes sense that those inputs would cause panics, since we can't have a cipher with a width of zero, but the error messages could be more clear. I added some asserts to address that: 8587b1f2206d5f609f95b5d9071a4a984e5bb4b1.

**Comment by lizhuohua** [comment]
Thanks for your reply! The assertions are helpful.
